function mibirthdayyearfunc() {
    console.log("naci en " + 1980);
}
//  naci en 1980  //


function myBirthYearFunc(EntradaAñoNacimiento){
    console.log("Nací en " + EntradaAñoNacimiento);
}
// Naci en 2005 //

function add(num1, num2){
    console.log("¡Sumando números!");
    console.log("num1 is: " + num1);
    console.log("num2 is: " + num2);
    var sum = num1 + num2;
    console.log(sum);
}
// ¡Sumando números!
instrument.ts:129 num1 is: 10
instrument.ts:129 num2 is: 20
instrument.ts:129 30 //